name: Test
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint and tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Check
        run: cargo check

      - name: Clippy
        run: cargo clippy

      - name: Test
        run: cargo test

  version_check:
    runs-on: ubuntu-latest
    name: Version Update Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install check tool
        run: |
          wget -q https://github.com/dbradf/pypi-version-check/releases/download/v0.3.0/pypi-version-check
          chmod +x pypi-version-check

      - name: Check Version
        run: |
          ./pypi-version-check --publish-type github-release --package-type rust --check-changelog
